name: "training config"
total_epoch: 20
save_per_count: 50
batch_size: 4
lr: 1e-3
device: 'auto' # ['cuda','mps','cpu'] 'auto' means check by list
save_file: 'auto' # auto means time format file name
load_file: ''
